### ISSUE TITLE
Add distance and remote unit IP to config

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-rpi-package#13]
Add distance and remote unit IP to config

**Comment by kostko** [comment]
Remote unit IP config added in 7b303cfa766282aa38118226576eeff63c9fd4dd.

The remote IP can be set by using:
```
sudo uci set koruza.@network[0].peer=10.10.254.101
```

The IP can be later retrieved in the script by accessing `local_status['network']['peer']`. Distance is currently already available in `local_status['camera_calibration']['distance']` (it should probably be moved, but it should do for now).
