### ISSUE TITLE
Webcam image rotate for 180deg and configure zoom

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-rpi-package#16]
How to rotate the image for 180deg and configure zoom level. Binocular configuration has changed and webcam must be adjusted accordingly.

**Comment by kostko** [comment]
Should this be configurable, e.g. so that you can set in uci whether the image is flipped or not?

**Comment by SloMusti** [comment]
This should  be configurable though uci, since it is different between unit versions and we need backwards compatibility.
