### ISSUE TITLE
Expose ubus for remote measurement access

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/koruza-rpi-package#2]
Enable ubus to be exposed on an URL, such that we can remote access the measurements.

**Comment by kostko** [comment]
It is already exposed under `/ubus`. You can talk to it using the JSON-RPC protocol over HTTP. Read-only access to the current state is possible to unauthenticated users, but for anything more you need to be authenticated.

For details on the JSON-RPC protocol used, see the UI:
* [UBUS JSON-RPC API](https://github.com/IRNAS/koruza-ui/blob/master/src/app/services/ubus.ts)

**Comment by SloMusti** [comment]
Please prepare an example Python script to collect the data.

**Comment by kostko** [comment]
Added in f281fed07e421d5bdef8653d4502f87748e755be.
